# Generated by Django 4.1 on 2022-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='agency/img/demos/seo-2/blog/default.png', upload_to='agency/img/demos/seo-2/blog'),
        ),
    ]
