# Generated by Django 4.1 on 2022-12-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Advance', 'Advance')], default='Normal', max_length=50),
        ),
    ]
